#
# Models
#
# Free tier:
# - https://openrouter.ai/models?max_price=0
# - https://aistudio.google.com/app/prompts/new_chat
# - https://github.com/marketplace?type=models
#
# Rankings:
# - https://openrouter.ai/rankings/programming?view=day
# - https://aider.chat/docs/leaderboards/
#
model: main
weak-model: weak
editor-model: main
show-model-warnings: false
alias:
    # - "main:openrouter/deepseek/deepseek-r1:free"
    # - "main:openai/o4-mini"
    # - "main:github/Codestral-2501"
    # - "main:github/gpt-4o-mini"
    - "main:gemini/gemini-2.5-flash-lite"
    - "weak:gemini/gemini-2.0-flash-lite"
    - "gemini:gemini/gemini-2.5-flash"
    - "deepseek:openrouter/deepseek/deepseek-chat-v3-0324:free"
    - "codestral:github/Codestral-2501"
    - "cohere:cohere_chat/command-a-03-2025"

env-file: /home/oleg/.secrets/envs
set-env:
    - HTTPS_PROXY=127.0.0.1:18080
    - GOOGLE_GENAI_USE_VERTEXAI=false

cache-prompts: true

watch-files: false

git: true
auto-commits: false
# Use global gitignore
gitignore: false

aiderignore: /home/oleg/.config/git/ignore

read: AGENTS.md
