#!/usr/bin/env zsh

symfony_local() {
	echo -n "# https://symfony.com/doc/current/setup/symfony_server.html#configuration-file

# proxy:
#   domains:
#     - '${1}'

workers:
  # Auto start Docker compose when starting server
  # docker_compose: ~
  #
  # mailpit:
  #    cmd: ['mailpit']

  artisan:queue:
    cmd: ['symfony', 'php', 'artisan',  'queue:listen', '--tries=1']

  vite:
    cmd: ['npm', 'run', 'dev']"
}

aider_conf() {
    echo -n 'lint-cmd: "symfony php vendor/bin/pint --test"
test-cmd: "symfony php artisan test"'
}

install_pest() {
    # https://pestphp.com/docs/installation
    symfony composer remove --dev phpunit/phpunit &&
    symfony composer require pestphp/pest pestphp/pest-plugin-laravel --dev --with-all-dependencies &&
    yes 'no' | symfony php vendor/bin/pest --init &&
    find tests -iname ExampleTest.php -delete
}

composer create-project laravel/laravel . &&
    rsync --recursive "${PROJECTS}/.templates/laravel/" ./ &&
    rm bootstrap/cache/*.php && symfony composer remove --dev laravel/sail &&
    install_pest &&
    npm install &&
    symfony_local "${PWD##*/}" > .symfony.local.yaml &&
    aider_conf > .aider.conf.yml &&
    git init && git add . && git commit -m 'Initial commit' >/dev/null
