#!/usr/bin/env zsh

symfony_local() {
	echo -n "# https://symfony.com/doc/current/setup/symfony_server.html#configuration-file

proxy:
  domains:
    - '${1}'

workers:
  # Auto start Docker compose when starting server
  # docker_compose: ~

  vite:
    cmd: ['./node_modules/.bin/vite']"
}

install_pest() {
    # https://pestphp.com/docs/installation
	composer remove --dev phpunit/phpunit &&
    composer require pestphp/pest pestphp/pest-plugin-laravel --dev --with-all-dependencies &&
    yes 'no' | vendor/bin/pest --init &&
    find tests -iname ExampleTest.php -delete &&
    sed -iE \
        -e 's@<!-- <env name="DB_CONNECTION" value="sqlite"/> -->@<env name="DB_CONNECTION" value="sqlite"/>@' \
        -e 's@<!-- <env name="DB_DATABASE" value=":memory:"/> -->@<env name="DB_DATABASE" value=":memory:"/>@' \
            phpunit.xml
}

composer create-project laravel/laravel . &&
	composer remove --dev laravel/sail &&
    install_pest &&
	symfony_local "${PWD##*/}" > .symfony.local.yaml &&
    git init
