#!/usr/bin/env zsh

mkdir src specs

echo '
{
    "autoload": {
        "psr-4": {
            "App\\\": "src/"
        }
    }
}' > composer.json

composer require --dev peridot-php/peridot-jumpstart
wget https://raw.githubusercontent.com/peridot-php/peridot-jumpstart/master/peridot.php
