#!/usr/bin/env zsh

mkdir src tests

echo '{
    "autoload": {
        "psr-4": {
            "App\\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\\Tests\\\": "tests/"
        }
    }
}' > composer.json
composer dump

echo '/vendor/' > .gitignore
