#!/usr/bin/env zsh

readonly php_version=8.1

ddev config \
    --project-type=php \
    --php-version="${php_version}" \
    --docroot=public \
    --create-docroot \
    --omit-containers=db,dba && \
    ddev composer create -y symfony/skeleton && \
    # https://dev.to/devtonight/how-to-fix-npm-timeout-errors-on-slow-internet-connections-2kn4
    ddev exec npm config set fetch-retries 3 && \
    ddev exec npm config set fetch-retry-mintimeout 100000 && \
    ddev exec npm config set fetch-retry-maxtimeout 600000 && \
    ddev exec npm config set cache-min 3600 && \
