#!/usr/bin/env zsh

createBabelConfig() {
    cat > babel.config.js <<EOF
module.exports = {
    presets: [[ '@babel/preset-env', { targets: { node: 'current' }} ]],
};
EOF
}

createJestConfig() {
    cat > jest.config.js <<EOF
module.exports = {
    moduleFileExtensions: [ 'js', 'json', 'vue' ],
    transform: {
        '\\.[jt]sx?$': 'babel-jest',
        '.*\.(vue)$': 'vue-jest',
   }
};
EOF
}

yarn create vite-app . && \
    echo '' > src/App.vue && \
    echo '' > src/index.css && \
    rm -rf src/assets/ src/components/ && \
    yarn install && \
    yarn add --dev jest babel-jest @babel/core @babel/preset-env @vue/test-utils vue-jest && \
    createBabelConfig && \
    createJestConfig
