#!/usr/bin/env zsh

echo "${PWD##*/}" | \
    npm init -- vite --template vue . && \
    echo '' > src/App.vue && \
    echo '' > src/index.css && \
    rm -rf src/assets/ src/components/ && \
    npm install
