#!/usr/bin/env zsh

"${0:a:h}/vue" && \
    npm install -D tailwindcss postcss autoprefixer && \
    npx tailwindcss init -p && \
    rm src/index.css && \
    echo -e "import 'tailwindcss/tailwind.css'\n\n$(cat src/main.js)" > src/main.js
