#!/usr/bin/env zsh

"${0:a:h}/vue" && \
    yarn add -D tailwindcss@latest postcss@latest autoprefixer@latest && \
    yarn tailwind init -p && \
    rm src/index.css && \
    echo -e "import 'tailwindcss/tailwind.css'\n\n$(cat src/main.js)" > src/main.js
