#!/usr/bin/env zsh

extra_packages=(
    'wpackagist-plugin/autoptimize'
    'wpackagist-plugin/html-editor-syntax-highlighter'
    'wpackagist-plugin/slim-seo'
    'wpackagist-plugin/surge'
)

export BADROCK_EXTRA_PACKAGES="${BADROCK_EXTRA_PACKAGES} ${extra_packages}"

badrock
