#!/usr/bin/env zsh

dotenvs() {
    cat > .env << 'ENV'
WP_ENV=development
WP_HOME=${DDEV_PRIMARY_URL}
DB_HOST=db
DB_NAME=db
DB_USER=db
DB_PASSWORD=db
ENV
}

wordpress_install() {
    ddev wp core install \
        --url="\${DDEV_PRIMARY_URL}" \
        --title="${WP_TITLE:-${PWD##*/}}" \
        --admin_user="${WP_USER:-admin}" \
        --admin_password="${WP_PASSWORD:-admin}" \
        --admin_email="${WP_EMAIL:-oleg-voronkovich@yandex.ru}"
}

plugins_configure() {
    ddev composer config --json 'extra.installer-paths.web/app/mu-plugins/{$name}/' $'[
        "type:wordpress-muplugin",
        "johnbillion/query-monitor",
        "roots/soil",
        "wpackagist-plugin/query-monitor",
        "wpackagist-plugin/soil"
    ]'
}

plugins_install() {
    ddev composer require --dev \
        'johnbillion/query-monitor' \
        'symfony/var-dumper' \

    ddev composer require \
        'roots/soil' \
        'wpackagist-plugin/autoptimize' \
        'wpackagist-plugin/html-editor-syntax-highlighter' \
        'wpackagist-plugin/surge' \
}

ddev config --project-type=wordpress --disable-settings-management \
    && ddev start \
    && echo '{}' > composer.json \
    && ddev composer config --no-plugins allow-plugins.composer/installers true \
    && ddev composer config --no-plugins allow-plugins.johnpbloch/wordpress-core-installer true \
    && ddev composer config --no-plugins allow-plugins.wecodemore/wpstarter true \
    && ddev composer require \
        'johnpbloch/wordpress' \
        'wecodemore/wpstarter:^3@dev' \
    && dotenvs \
    && wordpress_install \
    # && plugins_configure \
    # && plugins_install \
